# Generated by Django 5.2.5 on 2025-08-10 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'responder', 'offered_item', 'requested_item', 'status'), name='uniq_pending_trade_per_pair'),
        ),
    ]
