# Generated by Django 5.2.5 on 2025-08-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Görsel açıklaması (SEO için)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Gösterim sırası')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.item')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
