# Generated by Django 5.2.5 on 2025-08-10 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_itemimage_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_weights', models.JSONField(default=dict, help_text='Kategori ağırlıkları {kategori: weight}')),
                ('avg_response_time', models.FloatField(default=24.0, help_text='Ortalama yanıt süresi (saat)')),
                ('trade_success_rate', models.FloatField(default=0.0, help_text='Takas başarı oranı (0-1)')),
                ('activity_score', models.FloatField(default=0.0, help_text='Aktivite skoru (0-100)')),
                ('preferred_item_age_min', models.IntegerField(default=0, help_text='Minimum ürün yaşı (gün)')),
                ('preferred_item_age_max', models.IntegerField(default=365, help_text='Maksimum ürün yaşı (gün)')),
                ('max_distance', models.IntegerField(default=50, help_text='Maksimum mesafe (km)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Tercihi',
                'verbose_name_plural': 'Kullanıcı Tercihleri',
            },
        ),
        migrations.CreateModel(
            name='MatchRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Eşleşme skoru (0-100)')),
                ('recommendation_type', models.CharField(choices=[('perfect_match', 'Mükemmel Eşleşme'), ('high_potential', 'Yüksek Potansiyel'), ('category_match', 'Kategori Eşleşmesi'), ('user_behavior', 'Davranış Bazlı'), ('trending', 'Trend Bazlı')], max_length=20)),
                ('confidence_level', models.FloatField(help_text='Güven seviyesi (0-1)')),
                ('reasoning', models.JSONField(default=dict, help_text='Öneri gerekçeleri')),
                ('is_shown', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_converted', models.BooleanField(default=False, help_text='Takasa dönüştü mü?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='market.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('user_item', models.ForeignKey(blank=True, help_text='Kullanıcının karşılık verebileceği ürün', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potential_trades', to='market.item')),
            ],
            options={
                'verbose_name': 'Takas Önerisi',
                'verbose_name_plural': 'Takas Önerileri',
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_shown'], name='market_matc_user_id_756b66_idx'), models.Index(fields=['match_score'], name='market_matc_match_s_a40754_idx'), models.Index(fields=['created_at'], name='market_matc_created_a0c5ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Görüntüleme'), ('favorite', 'Favorileme'), ('unfavorite', 'Favoriden Çıkarma'), ('trade_request', 'Takas Teklifi'), ('trade_accept', 'Takas Kabul'), ('trade_reject', 'Takas Red'), ('swipe_right', 'Sağa Kaydırma (Beğeni)'), ('swipe_left', 'Sola Kaydırma (Beğenmeme)'), ('message_send', 'Mesaj Gönderme')], max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Yanıt süresi (saniye)', null=True)),
                ('session_duration', models.FloatField(blank=True, help_text='Oturum süresi (saniye)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='market.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Etkileşimi',
                'verbose_name_plural': 'Kullanıcı Etkileşimleri',
                'indexes': [models.Index(fields=['user', 'created_at'], name='market_user_user_id_933e31_idx'), models.Index(fields=['item', 'interaction_type'], name='market_user_item_id_0ccc30_idx'), models.Index(fields=['created_at'], name='market_user_created_5da0b4_idx')],
            },
        ),
    ]
