# Generated by Django 5.2.5 on 2025-08-10 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0006_userpreference_matchrecommendation_userinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Online Durumu',
                'verbose_name_plural': 'Kullanıcı Online Durumları',
            },
        ),
        migrations.CreateModel(
            name='LiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('item_created', '🆕 Yeni Ürün'), ('trade_created', '🔄 Yeni Takas'), ('trade_completed', '✅ Takas Tamamlandı'), ('user_joined', '👋 Yeni Üye'), ('item_favorited', '❤️ Ürün Beğenildi'), ('recommendation_clicked', '🎯 Öneri Tıklandı'), ('user_online', '🟢 Kullanıcı Online')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canlı Aktivite',
                'verbose_name_plural': 'Canlı Aktiviteler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='market_live_created_45766b_idx'), models.Index(fields=['activity_type'], name='market_live_activit_d99b4a_idx'), models.Index(fields=['is_public'], name='market_live_is_publ_491a53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('trade_request', 'Takas Teklifi'), ('trade_accepted', 'Takas Kabul Edildi'), ('trade_rejected', 'Takas Reddedildi'), ('new_message', 'Yeni Mesaj'), ('item_liked', 'Ürününüz Beğenildi'), ('new_recommendation', 'Yeni Öneri'), ('system_update', 'Sistem Güncellemesi'), ('trade_reminder', 'Takas Hatırlatması'), ('profile_view', 'Profil Görüntülendi')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_push_sent', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.URLField(blank=True, help_text='Tıklandığında gidilecek URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='market_noti_recipie_f16b6e_idx'), models.Index(fields=['created_at'], name='market_noti_created_0e34ae_idx'), models.Index(fields=['notification_type'], name='market_noti_notific_e5623a_idx')],
            },
        ),
    ]
